// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi7JTB6U1QLaHGuG2u8tg67XyC7gRyyVc',
    appId: '1:821168628456:web:7b86cec00f5b955e929f5d',
    messagingSenderId: '821168628456',
    projectId: 'pesan-keranjang',
    authDomain: 'pesan-keranjang.firebaseapp.com',
    storageBucket: 'pesan-keranjang.firebasestorage.app',
    measurementId: 'G-THYZSRNT5X',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnP9UwoB6L8ssoLgA5dZJN3cvBt8yDT88',
    appId: '1:821168628456:ios:f7f2b0a9c2bb9930929f5d',
    messagingSenderId: '821168628456',
    projectId: 'pesan-keranjang',
    storageBucket: 'pesan-keranjang.firebasestorage.app',
    iosBundleId: 'com.example.pesanKeranjangClient',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnP9UwoB6L8ssoLgA5dZJN3cvBt8yDT88',
    appId: '1:821168628456:ios:f7f2b0a9c2bb9930929f5d',
    messagingSenderId: '821168628456',
    projectId: 'pesan-keranjang',
    storageBucket: 'pesan-keranjang.firebasestorage.app',
    iosBundleId: 'com.example.pesanKeranjangClient',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0oNWOY9f_fUf3u6nNg3hr6lL-Ngfeww4',
    appId: '1:821168628456:android:1cb4bff02ad74344929f5d',
    messagingSenderId: '821168628456',
    projectId: 'pesan-keranjang',
    storageBucket: 'pesan-keranjang.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi7JTB6U1QLaHGuG2u8tg67XyC7gRyyVc',
    appId: '1:821168628456:web:01e8cf30a666d1d8929f5d',
    messagingSenderId: '821168628456',
    projectId: 'pesan-keranjang',
    authDomain: 'pesan-keranjang.firebaseapp.com',
    storageBucket: 'pesan-keranjang.firebasestorage.app',
    measurementId: 'G-RJCVCG77M1',
  );

}