name: Build Release APK

on:
  push:
    branches:
      - main # Akan berjalan saat ada push ke branch main
  workflow_dispatch: # Mengizinkan Anda untuk menjalankan workflow secara manual dari tab Actions

permissions:
  contents: write # Wajib agar GitHub Actions diizinkan membuat Tag & Release

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17' # Versi Java yang direkomendasikan untuk build Android terbaru

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Auto Versioning)
        # Menimpa versi pubspec dengan versi dari GitHub Run Number
        run: flutter build apk --release --build-name=1.0.${{ github.run_number }} --build-number=${{ github.run_number }}

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk "build/app/outputs/flutter-apk/Pesan Keranjang.apk"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pesan Keranjang APK
          path: "build/app/outputs/flutter-apk/Pesan Keranjang.apk"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          files: "build/app/outputs/flutter-apk/Pesan Keranjang.apk"
          draft: false
          prerelease: false